---
- name: inotify-tools package
  apt: pkg=inotify-tools state=latest update_cache=yes

- name: install nodejs and npm
  apt:
    state: latest
    pkg:
      - nodejs
      - npm

- name: install local.hex package manager
  become_user: vagrant
  become: yes
  shell: mix local.hex --force
  args:
    creates: /home/vagrant/.mix/archives/hex.ez

- name: install phoenix
  become_user: vagrant
  become: yes
  shell: mix archive.install hex phx_new 1.5.7 --force
