---
- name: install packages
  apt:
    state: latest
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - postgresql
      - libpq-dev
  # postgresql package requires correct locale when installing
  environment:
    LC_ALL: en_US.UTF-8
    
- name: ensure postgresql is running
  service: name=postgresql state=started enabled=yes

# Ensure that postgresql is restarted before we create databases and users
- meta: flush_handlers
